apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: nestjs-app
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "3"
    spec:
      containerConcurrency: 100
      containers:
      - image: gcr.io/rubik-web-app-1540579753013/nestjs-app
        ports:
        - containerPort: 3000
        env:
          - name: DATABASE_SCHEMA
            valueFrom:
              secretKeyRef:
                key: POSTGRES_DB
                name: nest-postgres-secret
          - name: DATABASE_USER
            valueFrom:
              secretKeyRef:
                key: POSTGRES_USER
                name: nest-postgres-secret
          - name: DATABASE_PASS
            valueFrom:
              secretKeyRef:
                key: POSTGRES_PASSWORD
                name: nest-postgres-secret
          - name: DATABASE_HOST
            valueFrom:
              configMapKeyRef:
                key: DATABASE_HOST
                name: nest-postgres-config
          - name: DATABASE_PORT
            valueFrom:
              configMapKeyRef:
                key: DATABASE_PORT
                name: nest-postgres-config
        resources:
          limits:
            memory: 256Mi
            cpu: 100m
