apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: nest-postgres
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nest-postgres
  minReplicas: 1
  maxReplicas: 3